# SEE AN EXAMPLE AT https://github.com/MinecraftForge/MinecraftForge/blob/1.14.x/mods.toml

# The name of the mod loader type to load
modLoader="javafml"
# A version range to match for said mod loader
loaderVersion="[26,)"
# A URL to query for updates
#updateJSONURL="http://myurl.me/"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/MinecraftModDevelopmentMods/Extra-Golems/issues"

[[mods]]
    modId="golems"
    version="10.2.2"
    displayName="Extra Golems"
    credits="TheGlitch76, jriwanek, AtelierAmber, and translators - Thanks!"
    authors="skyjay1 and the MMD Team"
    description='''Adds dozens of golems to the minecraft universe, each with unique textures and abilities!'''
    logoFile="golem_logo.png"
[[dependencies.golems]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.golems]]
    modId="quark"
    mandatory=false
    versionRange="[42.1-237,)"
    ordering="AFTER"
    side="BOTH"
