# SEE AN EXAMPLE AT https://github.com/MinecraftForge/MinecraftForge/blob/1.13.x/mods.toml

# The name of the mod loader type to load
modLoader="javafml"
# A version range to match for said mod loader
loaderVersion="[2.0,)"
# A URL to query for updates
#updateJSONURL="http://myurl.me/"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/MinecraftModDevelopmentMods/Extra-Golems/issues"
logoFile="golem_logo.png"

[[mods]]
    modId="golems"
    version="8.0.0-beta01"
    displayName="Extra Golems"
    credits="TheGlitch76, jriwanek, and translators - Thanks!"
    authors="skyjay1 and the MMD Team"
    description='''
    Adds 35+ golems to the minecraft universe, each with unique textures and abilities!
    '''
    [[dependencies.golems]]
        modId="forge"
        mandatory=true
        versionRange="[25.0.110,)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.examplemod]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.13.2]"
        ordering="NONE"
        side="BOTH"