# SEE AN EXAMPLE AT https://github.com/MinecraftForge/MinecraftForge/blob/1.14.x/mods.toml

# The name of the mod loader type to load
modLoader="javafml"
# A version range to match for said mod loader
loaderVersion="[26,)"
# A URL to query for updates
#updateJSONURL="http://myurl.me/"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/MinecraftModDevelopmentMods/Extra-Golems/issues"

[[mods]]
    modId="golems"
    version="9.0.6"
    displayName="Extra Golems"
    credits="TheGlitch76, jriwanek, and translators - Thanks!"
    authors="skyjay1 and the MMD Team"
    description='''
    Adds dozens of golems to the minecraft universe, each with unique textures and abilities!
    '''
    logoFile="golem_logo.png"
[[dependencies.golems]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
